import { IProduct } from "@/src/types/general";
import { mockCategories } from "./mockCategories";

export const mockProducts: IProduct[] = [
  {
    id: "M1001",
    name: "Paracetamol 500mg",
    description: "Analgésico y antipirético utilizado para aliviar dolores leves a moderados y reducir la fiebre.",
    category: mockCategories[0].name,
    originalPrice: 2990,
    offerPercentage: 10,
    stocks: 120,
    images: [
      "https://placehold.co/600x400.png?text=Paracetamol",
      "https://placehold.co/600x400.png?text=Tabletas",
    ],
    isPublished: true,
    rating: 4.5,
    ratingCount: 210,
    requiresPrescription: false,
    laboratory: "Bayer",
    activeIngredient: "Paracetamol",
    dosage: "500mg",
    format: "Tabletas",
    features: ["Alivia dolor", "Reduce fiebre", "Uso común"],
  },
  {
    id: "M1002",
    name: "Ibuprofeno 400mg",
    description: "Antiinflamatorio no esteroide (AINE) usado para dolor muscular, fiebre e inflamación.",
    category: mockCategories[0].name,
    originalPrice: 3990,
    offerPercentage: 15,
    stocks: 80,
    images: [
      "https://placehold.co/600x400.png?text=Ibuprofeno",
      "https://placehold.co/600x400.png?text=Capsulas",
    ],
    isPublished: true,
    rating: 4.6,
    ratingCount: 180,
    requiresPrescription: false,
    laboratory: "Saval",
    activeIngredient: "Ibuprofeno",
    dosage: "400mg",
    format: "Tabletas",
    features: ["Antiinflamatorio", "Alivio rápido", "Dolor muscular"],
  },
  {
    id: "M1003",
    name: "Amoxicilina 500mg",
    description: "Antibiótico utilizado para tratar infecciones bacterianas.",
    category: mockCategories[1].name,
    originalPrice: 6990,
    offerPercentage: 5,
    stocks: 40,
    images: [
      "https://placehold.co/600x400.png?text=Amoxicilina",
      "https://placehold.co/600x400.png?text=Antibiotico",
    ],
    isPublished: true,
    rating: 4.7,
    ratingCount: 95,
    requiresPrescription: true,
    laboratory: "ChileLab",
    activeIngredient: "Amoxicilina",
    dosage: "500mg",
    format: "Cápsulas",
    features: ["Antibiótico", "Tratamiento infecciones"],
  },
  {
    id: "M1004",
    name: "Jarabe para la Tos",
    description: "Jarabe que alivia la tos seca y productiva.",
    category: mockCategories[2].name,
    originalPrice: 5490,
    offerPercentage: 10,
    stocks: 60,
    images: [
      "https://placehold.co/600x400.png?text=Jarabe",
      "https://placehold.co/600x400.png?text=Tos",
    ],
    isPublished: true,
    rating: 4.3,
    ratingCount: 70,
    requiresPrescription: false,
    laboratory: "Mintlab",
    activeIngredient: "Dextrometorfano",
    dosage: "120ml",
    format: "Jarabe",
    features: ["Alivia tos", "Sabor agradable"],
  },
  {
    id: "M1005",
    name: "Vitamina C 1000mg",
    description: "Suplemento que refuerza el sistema inmunológico.",
    category: mockCategories[3].name,
    originalPrice: 4990,
    offerPercentage: 20,
    stocks: 150,
    images: [
      "https://placehold.co/600x400.png?text=Vitamina+C",
      "https://placehold.co/600x400.png?text=Efervescente",
    ],
    isPublished: true,
    rating: 4.8,
    ratingCount: 300,
    requiresPrescription: false,
    laboratory: "RedPharma",
    activeIngredient: "Ácido ascórbico",
    dosage: "1000mg",
    format: "Tabletas efervescentes",
    features: ["Refuerza defensas", "Fácil consumo"],
  },
  {
    id: "M1006",
    name: "Alcohol Gel 70%",
    description: "Gel desinfectante para manos sin necesidad de agua.",
    category: mockCategories[4].name,
    originalPrice: 1990,
    offerPercentage: 5,
    stocks: 200,
    images: [
      "https://placehold.co/600x400.png?text=Alcohol+Gel",
      "https://placehold.co/600x400.png?text=Desinfeccion",
    ],
    isPublished: true,
    rating: 4.4,
    ratingCount: 140,
    requiresPrescription: false,
    laboratory: "Softys",
    activeIngredient: "Alcohol etílico",
    dosage: "250ml",
    format: "Gel",
    features: ["Desinfección rápida", "Uso diario"],
  },
  {
    id: "M1007",
    name: "Termómetro Digital",
    description: "Termómetro digital para medición precisa de temperatura corporal.",
    category: mockCategories[5].name,
    originalPrice: 8990,
    offerPercentage: 10,
    stocks: 35,
    images: [
      "https://placehold.co/600x400.png?text=Termometro",
      "https://placehold.co/600x400.png?text=Digital",
    ],
    isPublished: true,
    rating: 4.5,
    ratingCount: 60,
    requiresPrescription: false,
    laboratory: "Omron",
    activeIngredient: "N/A",
    dosage: "N/A",
    format: "Dispositivo",
    features: ["Medición rápida", "Alta precisión"],
  },
];